### ISSUE TITLE
Not spawning robot in docker compose

### ISSUE THREAD

**Issue by m00nlab** [osrf/mbzirc#125]
Hello sir,

When bringing up a robot along with a simulator container using docker compose, the robot is not getting spawned into the environment. However the ros2 topic for the robot is active in the robot container. However, on manually launching the robot from another terminal, the robot becomes visible in the simulator container.

How to solve this?

**Comment by iche033** [comment]
I'll need a minimal example to reproduce the issue. 

Side note, we're creating a single launch file to launch simulation and spawn robots in https://github.com/osrf/mbzirc/pull/126. Maybe that helps. We'll have more instructions once the PR is merged.
