### ISSUE TITLE
Maximum Height of Camera Viewing

### ISSUE THREAD

**Issue by munachisonwadike** [osrf/mbzirc#134]
Greetings! 👋🏾
Small question regarding the max height in the Gazebo simulation please.
When we place a downward facing camera on the UAV, and fly it in a vertical takeoff direction, we stop being able to get frames from the drone at a certain altitude.
In other words, there appears to be a max height for flying the drone above which we will not get good quality **camera** images.
We were unable to find the specification of precisely what is this height, from the webinars.
Could you kindly let us know if there is a maximum camera altitude hard coded into the simulation? If so, what is this height?Are we permitted to change or modify this max camera altitude in the simulation?  Can we ask for it to be increased? 
Warm regards,

**Comment by iche033** [comment]
hi! The max flight height allowed by [local aviation regulation](https://u.ae/en/information-and-services/justice-safety-and-the-law/aviation-safety) is 400 feet / 121.96 meters. So when your UAV in simulation exceeds that height, a time penalty is first given. If it continues flying beyond this height and reach above ~146meters the simulator will freeze your UAV. 

I don't know if they will have exceptions for max flight height in the physical demonstration but in simulation we adhere to the local regulations and will not be able to increase the altitude unless permitted by the organizers.
