### ISSUE TITLE
How to Properly Remove a spawned drone from Gazebo

### ISSUE THREAD

**Issue by munachisonwadike** [osrf/mbzirc#148]
Dear Organizers,
Greetings! We would like to ask regarding the proper technique for remove a UAV from the simulation?
Right now we only were told the "spawn" command, but when we try to "unspawn" a drone by clicking "remove" in Gazebo, we get a lot of error messages in the coastal environment, and then we are unable to run packages until we restart the cost environment. 
Could you kindly advise us on the correct way to remove a drone for the Gazebo?
Warm regards,

**Comment by iche033** [comment]
hi, sorry we don't have a clean way to remove a vehicle from simulation (which involves unloading its plugins and terminating the bridge processes). That's a known issue upstream in Ignition. So for now, you'll unfortunately need to restart the simulation or spawn another UAV.
