### ISSUE TITLE
Coast Environment Dimensions

### ISSUE THREAD

**Issue by munachisonwadike** [osrf/mbzirc#153]
Hello,
We were working out path planning calculations, and noticed it says on the [[coast environment wiki](https://github.com/osrf/mbzirc/wiki/Running-the-coast-environment)] that the coast environment is 6km x 6km.
However, in the [[coast.sdf file](https://github.com/osrf/mbzirc/blob/main/mbzirc_ign/worlds/coast.sdf#L1397)] it says that the geofence is 3.1km x 3.1km (10km^2). 
Could you kindly shed some light on the relationship between these two dimension? Where do we make use of this 6km x 6km spec in the code?
Warm regards,

**Comment by iche033** [comment]
hi, this picture should help illustrates the dimensions (base station not shown here):

![mbzirc_competition_area](https://user-images.githubusercontent.com/4000684/174402711-e8e665c1-fe83-4c0c-b4da-70fb9f26f693.png)

We made the entire world 6km x 6km, edge to edge. The highlighted area in green is 3.1km x 3.1km (10km^2), which is the competition demonstration area and size of the geofence. Your path planning algorithm should stay within the green region.
