### ISSUE TITLE
The camera on the mbzirc_oberon7_arm does not spawn a topic

### ISSUE THREAD

**Issue by Bisssen** [osrf/mbzirc#172]
I think the camera on the oberon7 arm is broken in the latest version. I have used it in earlier version with no problems, but I cannot make the oberon7 arm camera topics appear after upgrading.

Actions:
Creating a new setup by following the README.md file.
Running: ros2 launch mbzirc_ros competition_local.launch.py ign_args:="-v 4 -r simple_demo.sdf"
Running: ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=usv x:=15 y:=-16.5 z:=0.3 R:=0 P:=0 Y:=0 arm:=mbzirc_oberon7_arm gripper:=mbzirc_suction_gripper

Expected behavior:
Two topic called "/usv/arm/wrist/optical/camera_info" and "/usv/arm/wrist/optical/image_raw" should appear

Observed behavior:
No topics related to the camera on the arm appears, and rqt_image_view is unable to locate any image topics.

The USV appears with arm and gripper. All other topics appear as normal, as far as I can see. Spawning payloads on the USV also works fine. The same behavior is observed in the coast environment

**Comment by iche033** [comment]
I think you're using the latest version from the `main` branch? The sensor payload on the arm is now configurable. You can specify it using `arm_payload_slot0` argument, e.g. `arm_payload_slot0:=mbzirc_hd_camera`. We added documentation in https://github.com/osrf/mbzirc/wiki/UAV-and-USV-Payload-Configurations. We'll be doing a release soon and will make sure to highlight the changes.

**Comment by Bisssen** [comment]
Ah okay. That works`
