### ISSUE TITLE
Can we configure the parameters of mbzirc_3d_lidar?

### ISSUE THREAD

**Issue by lvjunning1243015876** [osrf/mbzirc#189]
Hi, we want to change the 'samples', 'min_angle' and 'max_angle' of mbzirc_3d_lidar, is that allowed? In detail, we change the horizontal resolution to 0.1 degree and FOV to 90 degree, and change vertical scan to 128 and FOV to 40 degree. The following are the corresponding changes in the sdf file.
```
  <horizontal>
      <samples>900</samples>
      <resolution>1</resolution>
      <min_angle>-0.78539</min_angle>
      <max_angle>0.78539</max_angle>
  </horizontal>
  <vertical>
      <samples>128</samples>
      <resolution>1</resolution>
      <min_angle>-0.3490555</min_angle>
      <max_angle>0.3490555</max_angle>
  </vertical>
```

**Comment by iche033** [comment]
hi, unfortunately we're not able to support configuring these params unless specifically requested by the organizers. So as of now, such changes are not allowed.
