### ISSUE TITLE
Problems about streaming the video from the quadrotor to the /<robot_name>/mbzirc/target/stream/start

### ISSUE THREAD

**Issue by jiazk1226** [osrf/mbzirc#193]
Hi!

After the simulation starts, we identify the target vessel through the sensor(slot0) of the quadrotor_1, and send the video stream & detection results to the operator. We receive the 'vessel_id_success' through ros2 topic.

Then we use another sensor(slot3) on the very same UAV to detect small object. After we identify the object, we stop the previous video stream and report a new video stream and detection results. We received 'finished', which means that our task failed.

These two video streams have different frame_id. I wonder if the video sources of vessel detection & object detection have to be the same sensor?

Best regards.

**Comment by iche033** [comment]
hi, currently it works with the same camera. I've extended the logic to support switching cameras for reporting targets in #195. The PR depends on core ignition library changes. We'll make a new release with this soon.
