### ISSUE TITLE
max range of mbzirc_rf_long_range?

### ISSUE THREAD

**Issue by LvJohny** [osrf/mbzirc#200]
what is the maximum working distance of mbzirc_rf_long_range? We tested and found that sensor output 'param_*/model' does not contain UAVs over 1200m.

**Comment by iche033** [comment]
1200m is a little high. The regular RF range sensor should have a range of about 500m. The RF long range sensor should have a range of about 1000m. The error should go around +-5m for the regular sensor and +-20m for the long range approximately.
