### ISSUE TITLE
RGBD camera points cloud

### ISSUE THREAD

**Issue by fbenti** [osrf/mbzirc#211]
Hi,

I'm trying to get the point clouds given by the depth camera, however I'm finding trouble extracting the rgb values correctly.

I'm subscribing to the /quadrotor_1/slot3/points topic. In the respective PointField[] fields there is a description of the channels and their layout in the binary data blob (as shown in the picture below).
![pointcloud](https://user-images.githubusercontent.com/72797317/184844324-c080b51d-c76e-4f62-84fe-1ad9f1542fc2.png)

The 'point_step' field in the PointCloud2 message is equal to 24, meaning that each point cloud is represented by 24 bytes. Considering the description in the picture, i would expect that the x-y-z value are 4 bytes each and the remaining 12 are given by r-g-b values. Hence, looking at the last channel, 'rgb', I would expect it to start at offset 12 and having count = 3, meaning that there are 4 bytes for each channel, instead  of having offset=16 and count = 1.

**Comment by iche033** [comment]
the rgb values are 1 byte per channel. They are packed into 4 byte data type (7). So the first byte is `r`, second byte is `g`, etc.

**Comment by fbenti** [comment]
Yeah that was my guess, however since the point_step is 24 (bytes) and the rgb channel starts at offset 16, there should be something wrong.

**Comment by iche033** [comment]
I think the `rgb` value could in theory start at offset 12 and occupy the next 4 bytes. We won't change the behavior now though. In any case, the each point cloud occupies 16 out of 24 bytes and the rest are just padding. You'll just need to get the rgb values from offset 16 instead of offset 12.
