### ISSUE TITLE
ROS1 bridge from containers

### ISSUE THREAD

**Issue by jiazk1226** [osrf/mbzirc#212]
Hello, we asked a question earlier about the reduced image transmition rate from Ignition to ROS2 and then ROS1 . We then use the `ign_ros_bridge` to send sensor data such like the camera, imu and lidar, and `/clock `directly from ignition to ROS1, not through ROS2. It works fine and the frequency of sensor looks correct. We would like to ask if this is allowed in the final assessment? And how to use `ign_ros_bridge` package noetic(ros1) branch in docker to access the sensor data in MBZIRC’s simulator docker?

Thank you.

**Comment by iche033** [comment]
hi, in the final evaluation runs, our cloud simulation infrastructure will launch the bridge for you in a separate docker container.. Unfortunately you won't be able to use Ignition to ROS1 bridge. It's set up to run an Ignition to ROS2 bridge.
