### ISSUE TITLE
Image "osrf/mbzirc:cloudsim_bridge_latest" does not contains cycloneadds.xml

### ISSUE THREAD

**Issue by pine-s** [osrf/mbzirc#221]
![Screenshot from 2022-08-23 21-48-56](https://user-images.githubusercontent.com/48044309/186170889-e7518a2e-3290-43dd-b779-606884a9238f.png)
 We have found that the bridges executed from the docker compose died immediately because 'cycloneadds.xml' is not found in the "osrf/mbzirc:cloudsim_bridge_latest".

We've found modifying the image "osrf/mbzirc:cloudsim_bridge_latest" with dockerfile could solve the issue, and run our USV and drones as we intended. We want to check whether the previous test run was done without the shutdown of the bridge containers.
```
FROM osrf/mbzirc:mbzirc_sim_latest

RUN mkdir /home/developer/config
COPY run_bridge.bash ./
COPY cyclonedds.xml /home/developer/config/
ENTRYPOINT ["./run_bridge.bash"]
```

Thank you.

**Comment by pieniacy** [comment]
We experienced the exact same problem when we tried to run the docker compose setup on our infrastructure. Can we discuss this problem in this issue, so it's publicly available to everyone?

**Comment by iche033** [comment]
Posting my answer here in case it helps others. The original issue is about missing `cyclonedds.xml` in the bridge container.

If you don't see the `cyclonedds.xml` file in the bridge container, it could be that docker compose is not run from inside the `docker/compose` directory. There is a [cyclonedds.xml](https://github.com/osrf/mbzirc/blob/v4/docker/compose/cyclonedds.xml) file in that directory which gets mounted to the container by [this line](https://github.com/osrf/mbzirc/blob/v4/docker/compose/gen_docker_compose.py#L106). It uses the `.` current path. You can try changing this path to the absolute path of the `docker/compose` directory containing the `cyclonedds.xml` file.
