### ISSUE TITLE
CMake Error at CMakeLists.txt:121 (find_package):

### ISSUE THREAD

**Issue by criseyanginvaild** [osrf/mbzirc#231]
when i was use " IGNITION_VERSION=fortress colcon build --merge-install " to build my space i get this error:

![Screenshot from 2022-12-19 07-19-15](https://user-images.githubusercontent.com/118521534/208571143-260965f3-6619-4e87-944e-e346cb602bfb.png)

bye the way, when the fortress installed and i get this error:

![Screenshot from 2022-12-19 08-42-06](https://user-images.githubusercontent.com/118521534/208573851-70bd0b5e-caff-4fa8-b7f1-c59088e77712.png)

**Comment by criseyanginvaild** [comment]
sudo apt install ros-galactic-ament-cmake-pycodestyle

**Comment by criseyanginvaild** [comment]
according this method to solve other same problems and will succeed

**Comment by criseyanginvaild** [comment]
the second picture , i haven't got the answer . please , if you know ,tell me.   Thank you !

**Comment by iche033** [comment]
the 2nd to last line in the second picture shows that you're using a local copy of `libQt5Core.so.5`? Can you installing and using the system installed version of Qt5?

**Comment by criseyanginvaild** [comment]
okay, the question seems to be solved which the nvidia driver is bad and i use the ubuntu 20.04 commend driver
