### ISSUE TITLE
Question regarding the simulation phase rules

### ISSUE THREAD

**Issue by 0pf0r** [osrf/mbzirc#232]
Hi,
Is it possible to release the simulation phase rules/materials to everyone? Obviously, I know the challenge is already in the last stages of the finals, but I think it would make a great robotics learning/practicing material.
The custom sensors rules are the ones I'm looking for, as it is unclear whether the ones in the mbzirc_custom folder are allowed or not.

**Comment by iche033** [comment]
You'll need to check with the MBZIRC organizers to see if they are able to release the rules / materials.

As for custom sensors in the mbzirc_custom folder, I remember only the [mbzirc_naive_3d_scanning_radar](https://github.com/osrf/mbzirc/tree/main/mbzirc_custom/mbzirc_naive_3d_scanning_radar) was allowed in the simulation phase.

**Comment by 0pf0r** [comment]
Thank you.
